# Simple workflow for deploying static content to GitHub Pages
name: Download crowdin and generate pages

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  schedule:
    - cron: '0 0 */1 * *'

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Build Database
        env:
          CROWDIN_TOKEN: ${{ secrets.CROWDIN_TOKEN }}
        run: npm install && npm run gen_page
      
      - name: Generate Crowdin Contributors
        uses: andrii-bodnar/action-crowdin-contributors@c0bdc9a1e54b6a64e59f14c08b7432f69406910f
        with:
          svg: true
          svg_output_path: 'web_root/crowdin_contributors.svg'
          contributors_per_line: 8
          max_contributors: 32
          image_size: 16
          files: []
        env:
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJ_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_TOKEN }}

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'web_root'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
