name: Pull request check

on:
  pull_request:

jobs:
  mod-synchronize-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - name: Synchronize Mods
        run: npm install && npm run mod_sync
