name: Upload crowdin

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - mods/**
jobs:
  upload-crowdin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          
      - name: npm install
        run: npm install
        
      - name: npm run mod_upload
        env:
          CROWDIN_TOKEN: ${{ secrets.CROWDIN_TOKEN }}
        run: npm run mod_upload
