name: Upload crowdin

on:
  workflow_dispatch:
  workflow_call:

jobs:
  upload-crowdin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - name: Build Database
        env:
          CROWDIN_TOKEN: $${{ secrets.CROWDIN_TOKEN }}
        run: npm install && npm run mod_upload
